-- Extracción de resultados de criterios SST por columna cromatográfica.
--
-- Fuente: base de datos del LIMS (sistema de gestión de laboratorio).
-- Tablas del esquema HELIUM (Waters Empower o similar).
--
-- Salida: una fila por (columna, test, criterio) con:
--   CODE             -- identificador de la columna cromatográfica
--   EQUIPMENT_ID     -- equipo HPLC asociado
--   TEST_EXECUTION_ID
--   EXECUTION_DATE
--   RULE_NAME        -- sustancia / método analítico
--   PARAMETER_ID / PARAMETER_NAME  -- parámetro SST evaluado
--   ACTUAL_NUMERIC_VALUE / TARGET_NUMERIC_VALUE / COMPARATOR / PASSED

SELECT
    HELIUM_HPLC_COLUMN.CODE,
    helium_equipment.ID              AS EQUIPMENT_ID,
    TEST_EXECUTION_ID,
    HELIUM_TEST_EXECUTION.EXECUTION_DATE,
    HELIUM_SUBSTANCE.NAME            AS RULE_NAME,
    HELIUM_COLUMN_PARAMETER.ID       AS PARAMETER_ID,
    HELIUM_COLUMN_PARAMETER.NAME     AS PARAMETER_NAME,
    ACTUAL_NUMERIC_VALUE,
    TARGET_NUMERIC_VALUE,
    COMPARATOR,
    PASSED
FROM HELIUM_CRITERION_RESULT
INNER JOIN HELIUM_COLUMN_PARAMETER
    ON HELIUM_CRITERION_RESULT.PARAMETER_ID = HELIUM_COLUMN_PARAMETER.ID
INNER JOIN HELIUM_RULE_RESULT
    ON HELIUM_CRITERION_RESULT.RULE_RESULT_ID = HELIUM_RULE_RESULT.ID
INNER JOIN HELIUM_TEST_EXECUTION
    ON HELIUM_RULE_RESULT.TEST_EXECUTION_ID = HELIUM_TEST_EXECUTION.ID
INNER JOIN HELIUM_HPLC_COLUMN
    ON HELIUM_TEST_EXECUTION.HPLC_COLUMN_ID = HELIUM_HPLC_COLUMN.ID
INNER JOIN HELIUM_SUBSTANCE
    ON HELIUM_RULE_RESULT.SUBSTANCE_ID = HELIUM_SUBSTANCE.ID
INNER JOIN helium_equipment
    ON helium_test_execution.EQUIPMENT_ID = helium_equipment.ID
WHERE
    HELIUM_COLUMN_PARAMETER.ID IN (
        SELECT PARAMETER_ID
        FROM HELIUM_COLUMN_TEST_CRITERION
        INNER JOIN HELIUM_TEST_RULE
            ON HELIUM_COLUMN_TEST_CRITERION.TEST_RULE_ID = HELIUM_TEST_RULE.ID
        WHERE HELIUM_TEST_EXECUTION.TEST_DEFINITION_ID = HELIUM_TEST_RULE.TEST_DEFINITION_ID
    )
ORDER BY CODE, EXECUTION_DATE, TEST_EXECUTION_ID DESC;
